deployment:
  deployment_name: test-deploy
  app_label: test-app
  replicas: 1
  strategy-type: RollingUpdate
  affinity_key: works
  affinity_value: enable

spec:
  containers_name: test-container
  containers_image: trickstermaster/test-jenkins-ci-cd:94
  port: 80
  env:
    env_name: env-test-deploy
    env_values: balblabla

  resources_requests-memory: "64Mi"
  resources_requests-cpu: "250m"
  resources_limits-memory: "128Mi"
  resources_limits-cpu: "500m"

  volume_name: test-volume
  volumeMounts_mountPath: /usr/share/nginx/html/
    

service:
  service_name: test-jenkins-ci-cd-svc
  port: 80
  target_port: 80
  type: LoadBalancer

persistentVolumeClaim:
  persistent_volume_claim_name: test-pvc
  storage_class: longhorn
  access_modes: ReadWriteOnce
  size: 1Gi